/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedDeskRouteImport } from './routes/_authenticated/desk'
import { Route as AuthenticatedScoutRouteImport } from './routes/_authenticated/scout'
import { Route as AuthenticatedRewardsIndexRouteImport } from './routes/_authenticated/rewards/index'
import { Route as AuthenticatedRewardsAccountsRouteImport } from './routes/_authenticated/rewards/accounts'
import { Route as AuthenticatedRewardsAgentsRouteImport } from './routes/_authenticated/rewards/agents'
import { Route as AuthenticatedRewardsApprovalsRouteImport } from './routes/_authenticated/rewards/approvals'
import { Route as AuthenticatedRewardsCampaignsRouteImport } from './routes/_authenticated/rewards/campaigns'
import { Route as AuthenticatedRewardsEarningsRouteImport } from './routes/_authenticated/rewards/earnings'
import { Route as AuthenticatedRewardsPipelineRouteImport } from './routes/_authenticated/rewards/pipeline'
import { Route as ApiCronDeskCycleRouteImport } from './routes/api/cron/desk-cycle'
import { Route as ApiCronDeskExecuteRouteImport } from './routes/api/cron/desk-execute'
import { Route as ApiCronDeskUniverseRouteImport } from './routes/api/cron/desk-universe'
import { Route as ApiCronHlSyncRouteImport } from './routes/api/cron/hl-sync'
import { Route as ApiCronLiveReconcileRouteImport } from './routes/api/cron/live-reconcile'
import { Route as ApiCronSmCopyRouteImport } from './routes/api/cron/sm-copy'
import { Route as ApiCronSmDailyRouteImport } from './routes/api/cron/sm-daily'
import { Route as ApiCronSmDeepDiveRouteImport } from './routes/api/cron/sm-deep-dive'
import { Route as ApiCronSmTrackRouteImport } from './routes/api/cron/sm-track'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeskRoute = AuthenticatedDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoutRoute = AuthenticatedScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsIndexRoute =
  AuthenticatedRewardsIndexRouteImport.update({
    id: '/rewards/',
    path: '/rewards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsAccountsRoute =
  AuthenticatedRewardsAccountsRouteImport.update({
    id: '/rewards/accounts',
    path: '/rewards/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsAgentsRoute =
  AuthenticatedRewardsAgentsRouteImport.update({
    id: '/rewards/agents',
    path: '/rewards/agents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsApprovalsRoute =
  AuthenticatedRewardsApprovalsRouteImport.update({
    id: '/rewards/approvals',
    path: '/rewards/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsCampaignsRoute =
  AuthenticatedRewardsCampaignsRouteImport.update({
    id: '/rewards/campaigns',
    path: '/rewards/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsEarningsRoute =
  AuthenticatedRewardsEarningsRouteImport.update({
    id: '/rewards/earnings',
    path: '/rewards/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsPipelineRoute =
  AuthenticatedRewardsPipelineRouteImport.update({
    id: '/rewards/pipeline',
    path: '/rewards/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCronDeskCycleRoute = ApiCronDeskCycleRouteImport.update({
  id: '/api/cron/desk-cycle',
  path: '/api/cron/desk-cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDeskExecuteRoute = ApiCronDeskExecuteRouteImport.update({
  id: '/api/cron/desk-execute',
  path: '/api/cron/desk-execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDeskUniverseRoute = ApiCronDeskUniverseRouteImport.update({
  id: '/api/cron/desk-universe',
  path: '/api/cron/desk-universe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHlSyncRoute = ApiCronHlSyncRouteImport.update({
  id: '/api/cron/hl-sync',
  path: '/api/cron/hl-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLiveReconcileRoute = ApiCronLiveReconcileRouteImport.update({
  id: '/api/cron/live-reconcile',
  path: '/api/cron/live-reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSmCopyRoute = ApiCronSmCopyRouteImport.update({
  id: '/api/cron/sm-copy',
  path: '/api/cron/sm-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSmDailyRoute = ApiCronSmDailyRouteImport.update({
  id: '/api/cron/sm-daily',
  path: '/api/cron/sm-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSmDeepDiveRoute = ApiCronSmDeepDiveRouteImport.update({
  id: '/api/cron/sm-deep-dive',
  path: '/api/cron/sm-deep-dive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSmTrackRoute = ApiCronSmTrackRouteImport.update({
  id: '/api/cron/sm-track',
  path: '/api/cron/sm-track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/scout': typeof AuthenticatedScoutRoute
  '/rewards/accounts': typeof AuthenticatedRewardsAccountsRoute
  '/rewards/agents': typeof AuthenticatedRewardsAgentsRoute
  '/rewards/approvals': typeof AuthenticatedRewardsApprovalsRoute
  '/rewards/campaigns': typeof AuthenticatedRewardsCampaignsRoute
  '/rewards/earnings': typeof AuthenticatedRewardsEarningsRoute
  '/rewards/pipeline': typeof AuthenticatedRewardsPipelineRoute
  '/api/cron/desk-cycle': typeof ApiCronDeskCycleRoute
  '/api/cron/desk-execute': typeof ApiCronDeskExecuteRoute
  '/api/cron/desk-universe': typeof ApiCronDeskUniverseRoute
  '/api/cron/hl-sync': typeof ApiCronHlSyncRoute
  '/api/cron/live-reconcile': typeof ApiCronLiveReconcileRoute
  '/api/cron/sm-copy': typeof ApiCronSmCopyRoute
  '/api/cron/sm-daily': typeof ApiCronSmDailyRoute
  '/api/cron/sm-deep-dive': typeof ApiCronSmDeepDiveRoute
  '/api/cron/sm-track': typeof ApiCronSmTrackRoute
  '/rewards/': typeof AuthenticatedRewardsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/scout': typeof AuthenticatedScoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/rewards/accounts': typeof AuthenticatedRewardsAccountsRoute
  '/rewards/agents': typeof AuthenticatedRewardsAgentsRoute
  '/rewards/approvals': typeof AuthenticatedRewardsApprovalsRoute
  '/rewards/campaigns': typeof AuthenticatedRewardsCampaignsRoute
  '/rewards/earnings': typeof AuthenticatedRewardsEarningsRoute
  '/rewards/pipeline': typeof AuthenticatedRewardsPipelineRoute
  '/api/cron/desk-cycle': typeof ApiCronDeskCycleRoute
  '/api/cron/desk-execute': typeof ApiCronDeskExecuteRoute
  '/api/cron/desk-universe': typeof ApiCronDeskUniverseRoute
  '/api/cron/hl-sync': typeof ApiCronHlSyncRoute
  '/api/cron/live-reconcile': typeof ApiCronLiveReconcileRoute
  '/api/cron/sm-copy': typeof ApiCronSmCopyRoute
  '/api/cron/sm-daily': typeof ApiCronSmDailyRoute
  '/api/cron/sm-deep-dive': typeof ApiCronSmDeepDiveRoute
  '/api/cron/sm-track': typeof ApiCronSmTrackRoute
  '/rewards': typeof AuthenticatedRewardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/desk': typeof AuthenticatedDeskRoute
  '/_authenticated/scout': typeof AuthenticatedScoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rewards/accounts': typeof AuthenticatedRewardsAccountsRoute
  '/_authenticated/rewards/agents': typeof AuthenticatedRewardsAgentsRoute
  '/_authenticated/rewards/approvals': typeof AuthenticatedRewardsApprovalsRoute
  '/_authenticated/rewards/campaigns': typeof AuthenticatedRewardsCampaignsRoute
  '/_authenticated/rewards/earnings': typeof AuthenticatedRewardsEarningsRoute
  '/_authenticated/rewards/pipeline': typeof AuthenticatedRewardsPipelineRoute
  '/api/cron/desk-cycle': typeof ApiCronDeskCycleRoute
  '/api/cron/desk-execute': typeof ApiCronDeskExecuteRoute
  '/api/cron/desk-universe': typeof ApiCronDeskUniverseRoute
  '/api/cron/hl-sync': typeof ApiCronHlSyncRoute
  '/api/cron/live-reconcile': typeof ApiCronLiveReconcileRoute
  '/api/cron/sm-copy': typeof ApiCronSmCopyRoute
  '/api/cron/sm-daily': typeof ApiCronSmDailyRoute
  '/api/cron/sm-deep-dive': typeof ApiCronSmDeepDiveRoute
  '/api/cron/sm-track': typeof ApiCronSmTrackRoute
  '/_authenticated/rewards/': typeof AuthenticatedRewardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backtest'
    | '/desk'
    | '/scout'
    | '/rewards/accounts'
    | '/rewards/agents'
    | '/rewards/approvals'
    | '/rewards/campaigns'
    | '/rewards/earnings'
    | '/rewards/pipeline'
    | '/api/cron/desk-cycle'
    | '/api/cron/desk-execute'
    | '/api/cron/desk-universe'
    | '/api/cron/hl-sync'
    | '/api/cron/live-reconcile'
    | '/api/cron/sm-copy'
    | '/api/cron/sm-daily'
    | '/api/cron/sm-deep-dive'
    | '/api/cron/sm-track'
    | '/rewards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backtest'
    | '/desk'
    | '/scout'
    | '/'
    | '/rewards/accounts'
    | '/rewards/agents'
    | '/rewards/approvals'
    | '/rewards/campaigns'
    | '/rewards/earnings'
    | '/rewards/pipeline'
    | '/api/cron/desk-cycle'
    | '/api/cron/desk-execute'
    | '/api/cron/desk-universe'
    | '/api/cron/hl-sync'
    | '/api/cron/live-reconcile'
    | '/api/cron/sm-copy'
    | '/api/cron/sm-daily'
    | '/api/cron/sm-deep-dive'
    | '/api/cron/sm-track'
    | '/rewards'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backtest'
    | '/_authenticated/desk'
    | '/_authenticated/scout'
    | '/_authenticated/'
    | '/_authenticated/rewards/accounts'
    | '/_authenticated/rewards/agents'
    | '/_authenticated/rewards/approvals'
    | '/_authenticated/rewards/campaigns'
    | '/_authenticated/rewards/earnings'
    | '/_authenticated/rewards/pipeline'
    | '/api/cron/desk-cycle'
    | '/api/cron/desk-execute'
    | '/api/cron/desk-universe'
    | '/api/cron/hl-sync'
    | '/api/cron/live-reconcile'
    | '/api/cron/sm-copy'
    | '/api/cron/sm-daily'
    | '/api/cron/sm-deep-dive'
    | '/api/cron/sm-track'
    | '/_authenticated/rewards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCronDeskCycleRoute: typeof ApiCronDeskCycleRoute
  ApiCronDeskExecuteRoute: typeof ApiCronDeskExecuteRoute
  ApiCronDeskUniverseRoute: typeof ApiCronDeskUniverseRoute
  ApiCronHlSyncRoute: typeof ApiCronHlSyncRoute
  ApiCronLiveReconcileRoute: typeof ApiCronLiveReconcileRoute
  ApiCronSmCopyRoute: typeof ApiCronSmCopyRoute
  ApiCronSmDailyRoute: typeof ApiCronSmDailyRoute
  ApiCronSmDeepDiveRoute: typeof ApiCronSmDeepDiveRoute
  ApiCronSmTrackRoute: typeof ApiCronSmTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desk': {
      id: '/_authenticated/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AuthenticatedDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scout': {
      id: '/_authenticated/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof AuthenticatedScoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/': {
      id: '/_authenticated/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof AuthenticatedRewardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/accounts': {
      id: '/_authenticated/rewards/accounts'
      path: '/rewards/accounts'
      fullPath: '/rewards/accounts'
      preLoaderRoute: typeof AuthenticatedRewardsAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/agents': {
      id: '/_authenticated/rewards/agents'
      path: '/rewards/agents'
      fullPath: '/rewards/agents'
      preLoaderRoute: typeof AuthenticatedRewardsAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/approvals': {
      id: '/_authenticated/rewards/approvals'
      path: '/rewards/approvals'
      fullPath: '/rewards/approvals'
      preLoaderRoute: typeof AuthenticatedRewardsApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/campaigns': {
      id: '/_authenticated/rewards/campaigns'
      path: '/rewards/campaigns'
      fullPath: '/rewards/campaigns'
      preLoaderRoute: typeof AuthenticatedRewardsCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/earnings': {
      id: '/_authenticated/rewards/earnings'
      path: '/rewards/earnings'
      fullPath: '/rewards/earnings'
      preLoaderRoute: typeof AuthenticatedRewardsEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards/pipeline': {
      id: '/_authenticated/rewards/pipeline'
      path: '/rewards/pipeline'
      fullPath: '/rewards/pipeline'
      preLoaderRoute: typeof AuthenticatedRewardsPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/desk-cycle': {
      id: '/api/cron/desk-cycle'
      path: '/api/cron/desk-cycle'
      fullPath: '/api/cron/desk-cycle'
      preLoaderRoute: typeof ApiCronDeskCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/desk-execute': {
      id: '/api/cron/desk-execute'
      path: '/api/cron/desk-execute'
      fullPath: '/api/cron/desk-execute'
      preLoaderRoute: typeof ApiCronDeskExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/desk-universe': {
      id: '/api/cron/desk-universe'
      path: '/api/cron/desk-universe'
      fullPath: '/api/cron/desk-universe'
      preLoaderRoute: typeof ApiCronDeskUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/hl-sync': {
      id: '/api/cron/hl-sync'
      path: '/api/cron/hl-sync'
      fullPath: '/api/cron/hl-sync'
      preLoaderRoute: typeof ApiCronHlSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/live-reconcile': {
      id: '/api/cron/live-reconcile'
      path: '/api/cron/live-reconcile'
      fullPath: '/api/cron/live-reconcile'
      preLoaderRoute: typeof ApiCronLiveReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sm-copy': {
      id: '/api/cron/sm-copy'
      path: '/api/cron/sm-copy'
      fullPath: '/api/cron/sm-copy'
      preLoaderRoute: typeof ApiCronSmCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sm-daily': {
      id: '/api/cron/sm-daily'
      path: '/api/cron/sm-daily'
      fullPath: '/api/cron/sm-daily'
      preLoaderRoute: typeof ApiCronSmDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sm-deep-dive': {
      id: '/api/cron/sm-deep-dive'
      path: '/api/cron/sm-deep-dive'
      fullPath: '/api/cron/sm-deep-dive'
      preLoaderRoute: typeof ApiCronSmDeepDiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sm-track': {
      id: '/api/cron/sm-track'
      path: '/api/cron/sm-track'
      fullPath: '/api/cron/sm-track'
      preLoaderRoute: typeof ApiCronSmTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedDeskRoute: typeof AuthenticatedDeskRoute
  AuthenticatedScoutRoute: typeof AuthenticatedScoutRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRewardsAccountsRoute: typeof AuthenticatedRewardsAccountsRoute
  AuthenticatedRewardsAgentsRoute: typeof AuthenticatedRewardsAgentsRoute
  AuthenticatedRewardsApprovalsRoute: typeof AuthenticatedRewardsApprovalsRoute
  AuthenticatedRewardsCampaignsRoute: typeof AuthenticatedRewardsCampaignsRoute
  AuthenticatedRewardsEarningsRoute: typeof AuthenticatedRewardsEarningsRoute
  AuthenticatedRewardsPipelineRoute: typeof AuthenticatedRewardsPipelineRoute
  AuthenticatedRewardsIndexRoute: typeof AuthenticatedRewardsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedDeskRoute: AuthenticatedDeskRoute,
  AuthenticatedScoutRoute: AuthenticatedScoutRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRewardsAccountsRoute: AuthenticatedRewardsAccountsRoute,
  AuthenticatedRewardsAgentsRoute: AuthenticatedRewardsAgentsRoute,
  AuthenticatedRewardsApprovalsRoute: AuthenticatedRewardsApprovalsRoute,
  AuthenticatedRewardsCampaignsRoute: AuthenticatedRewardsCampaignsRoute,
  AuthenticatedRewardsEarningsRoute: AuthenticatedRewardsEarningsRoute,
  AuthenticatedRewardsPipelineRoute: AuthenticatedRewardsPipelineRoute,
  AuthenticatedRewardsIndexRoute: AuthenticatedRewardsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCronDeskCycleRoute: ApiCronDeskCycleRoute,
  ApiCronDeskExecuteRoute: ApiCronDeskExecuteRoute,
  ApiCronDeskUniverseRoute: ApiCronDeskUniverseRoute,
  ApiCronHlSyncRoute: ApiCronHlSyncRoute,
  ApiCronLiveReconcileRoute: ApiCronLiveReconcileRoute,
  ApiCronSmCopyRoute: ApiCronSmCopyRoute,
  ApiCronSmDailyRoute: ApiCronSmDailyRoute,
  ApiCronSmDeepDiveRoute: ApiCronSmDeepDiveRoute,
  ApiCronSmTrackRoute: ApiCronSmTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
